import os
import sys
import argparse as arg

if __package__:
    from .bmprofile_perfAI import ProfileParser
    from .exporters import PerfettoExporter, TxtExporter, SummaryExporter
    from .perfAI.perfAIDoc.run_doc import run_doc
else:
    # Support direct execution: python bigTpuProfile/main.py ...
    repository_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if repository_root not in sys.path:
        sys.path.insert(0, repository_root)
    from bigTpuProfile.bmprofile_perfAI import ProfileParser
    from bigTpuProfile.exporters import PerfettoExporter, TxtExporter, SummaryExporter
    from bigTpuProfile.perfAI.perfAIDoc.run_doc import run_doc

def profileArgParser():
    parser = arg.ArgumentParser()
    # yapf: disable
    parser.add_argument("input_dir", type=str, help="profile_data dir generated by bmruntime")
    parser.add_argument(
        "output_dir",
        nargs="?",
        default="profile_out",
        help="output dir that contains parsing result",
    )
    parser.add_argument('--tiu_freq', default=1000, type=int, help='set TIU Frequency(MHz)')
    parser.add_argument('--enable_doc', action='store_true', help='Generate doc file')
    parser.add_argument('--disable_summary', action='store_true', help='Disable generate summary')
    parser.add_argument('--trace_file', type=str, help="Trace file to merge pmu profile, used for tpu-trian profile interface")
    # yapf: enable
    return parser


def main():
    parser = profileArgParser()
    args = parser.parse_args()
    profile = ProfileParser().parse(args.input_dir)

    if not args.disable_summary:
        ex = SummaryExporter(profile)
        ex.gen_summary(args.output_dir, args.tiu_freq)
    ex = PerfettoExporter(profile)
    ex.to_perfetto(args.output_dir, args.tiu_freq, args.trace_file)

    if args.enable_doc:
        ex = TxtExporter(profile)
        ex.to_txt(args.output_dir, args.tiu_freq)
        target_dir = args.output_dir
        out_name = os.path.split(os.path.abspath(args.output_dir))[-1]
        print("Generate doc...")
        run_doc(
            os.path.abspath(target_dir),
            profile.num_cores,
            f'{out_name}.xlsx',
            0,
            1,
            0,
            0,
            args.input_dir,
        )

if __name__ == "__main__":
    main()
